INSERT INTO clientes(id,nombre,apellido,email,create_at) VALUES(1,'Walter','Abregu','abreguwalter0709@gmail.com','2017-09-28');
INSERT INTO clientes(id,nombre,apellido,email,create_at) VALUES(2,'Ashly','Aguilar','aguilarash@gmail.com','2010-01-11');
INSERT INTO clientes(id,nombre,apellido,email,create_at) VALUES(3,'Karen','Aguilar','aguilarash@gmail.com','2010-01-11');
INSERT INTO clientes(id,nombre,apellido,email,create_at) VALUES(4,'Ale','Aguilar','aguilarash@gmail.com','2010-01-11');
INSERT INTO clientes(id,nombre,apellido,email,create_at) VALUES(5,'Susan','Aguilar','aguilarash@gmail.com','2010-01-11');
INSERT INTO clientes(id,nombre,apellido,email,create_at) VALUES(6,'Maricielo','Aguilar','aguilarash@gmail.com','2010-01-11');
INSERT INTO clientes(id,nombre,apellido,email,create_at) VALUES(7,'Kela','Aguilar','aguilarash@gmail.com','2010-01-11');
INSERT INTO clientes(id,nombre,apellido,email,create_at) VALUES(8,'Cyntia','Aguilar','aguilarash@gmail.com','2010-01-11');
INSERT INTO clientes(id,nombre,apellido,email,create_at) VALUES(9,'Laura','Aguilar','aguilarash@gmail.com','2010-01-11');